"""Generate a {chronic disease -> worsening symptoms} dataset with the LLM.

For each chronic disease in the model-curated HK/Asia catalogue
(`llm/hk_asia_chronic_catalog.json`), ask the model (Gemma 4 via the Gemini API by
default - see `config.py`) for the patient-observable symptoms that signal the
disease is **worsening / decompensating**. The result is a simple JSON object:

    { "<disease name>": ["<symptom>", "<symptom>", ...], ... }

This is meant to power the daily phone-call / wearable check-ins: given a patient's
chronic conditions, the platform knows which warning signs to listen for.

Run from the repo root (with `GEMINI_API_KEY` set for the Gemma backend):

    # dry run - print the dataset, do not write
    python -m llm.generate_worsening_symptoms

    # write it to disk
    python -m llm.generate_worsening_symptoms --apply

Useful flags:
    --apply             write the dataset (default: dry run / print only)
    --out PATH          output file (default: llm/worsening_symptoms.json)
    --catalog PATH      disease catalogue to read names from (default: the HK/Asia one)
    --diseases A,B,C    use this explicit comma-separated list instead of the catalogue
    --offline           skip the model: emit a small built-in fallback dataset
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

from . import config
from .client import LLMClient

WORSENING_PROMPT_FILE = "chronic_worsening_symptoms_prompt.md"
DEFAULT_OUT = config.REPO_ROOT / "llm" / "worsening_symptoms.json"

# Used only with --offline (or if the model reply is unusable). The canonical
# dataset is generated by the model.
FALLBACK_SYMPTOMS = {
    "Essential hypertension": [
        "Severe headache", "Dizziness", "Blurred vision",
        "Chest tightness", "Shortness of breath", "Nosebleeds",
    ],
    "Type 2 diabetes mellitus": [
        "Excessive thirst", "Passing urine much more often", "Blurred vision",
        "Unexplained tiredness", "Slow-healing sores", "Numbness in the feet",
    ],
    "Heart failure": [
        "Increasing shortness of breath", "Breathless when lying flat",
        "Swelling in the ankles or legs", "Sudden weight gain over a few days",
        "Waking up at night gasping for air", "Persistent tiredness",
    ],
    "Chronic kidney disease": [
        "Passing much less urine", "Swelling in the legs or face",
        "Persistent itching", "Nausea or loss of appetite",
        "Unusual tiredness", "Shortness of breath",
    ],
    "COPD": [
        "Worsening cough", "More breathlessness than usual",
        "Coughing up more or discoloured phlegm", "Wheezing",
        "Chest tightness", "Needing the inhaler much more often",
    ],
}


def load_disease_names(catalog_path: Path, diseases_arg: str | None) -> list[str]:
    if diseases_arg:
        return [d.strip() for d in diseases_arg.split(",") if d.strip()]
    if not catalog_path.exists():
        sys.exit(
            f"No catalogue at {catalog_path}. Build it with "
            "`python -m llm.fix_chronic_conditions` first, or pass --diseases."
        )
    data = json.loads(catalog_path.read_text(encoding="utf-8"))
    names = [c["name"] for c in data.get("conditions", []) if c.get("name")]
    if not names:
        sys.exit(f"Catalogue at {catalog_path} has no conditions.")
    return names


def _ensure_credentials() -> None:
    if config.LLM_PROVIDER != "vllm" and not config.GEMINI_API_KEY:
        sys.exit(
            "No API key for the Gemma backend. Set GEMINI_API_KEY (or GOOGLE_API_KEY),\n"
            "or run with --offline, or LLM_PROVIDER=vllm against a local server.\n"
            "Get a key at https://aistudio.google.com/apikey"
        )


def _require_model(client: LLMClient) -> None:
    if not client.health():
        sys.exit(
            f"Cannot reach the model at {client.base_url} (model: {client.model}).\n"
            "Check the key/network, or use --offline."
        )


def generate(names: list[str], *, offline: bool, batch_size: int = 6) -> dict[str, list[str]]:
    if offline:
        print("Offline: using the built-in fallback symptom dataset.")
        return {n: FALLBACK_SYMPTOMS.get(n, []) for n in names}

    _ensure_credentials()
    client = LLMClient(prompt_file=WORSENING_PROMPT_FILE)
    _require_model(client)
    print(f"Generating worsening-symptom map for {len(names)} diseases with "
          f"'{client.model}' (batches of {batch_size})...")

    # Gemma 4 is a reasoning model: its <thought> block is large, so asking for
    # all diseases at once blows the token budget. Process in small batches and
    # merge the results.
    result: dict[str, list[str]] = {}
    for i in range(0, len(names), batch_size):
        batch = names[i : i + batch_size]
        print(f"  batch {i // batch_size + 1}: {', '.join(batch)}")
        user = (
            "Build the worsening-symptoms map for exactly these chronic diseases, "
            "using each name verbatim as the JSON key:\n\n"
            + "\n".join(f"- {n}" for n in batch)
        )
        try:
            obj = client.chat_json(user)
        except Exception as e:  # noqa: BLE001 - one bad batch shouldn't sink the run
            print(f"    ! batch failed ({e}); leaving these blank")
            for n in batch:
                result[n] = []
            continue
        if not isinstance(obj, dict):
            print(f"    ! non-object reply ({type(obj).__name__}); leaving blank")
            for n in batch:
                result[n] = []
            continue
        for n in batch:
            symptoms = obj.get(n) or []
            if not isinstance(symptoms, list):
                symptoms = []
            result[n] = [str(s).strip() for s in symptoms if str(s).strip()]
    return result


def main() -> None:
    ap = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    ap.add_argument("--apply", action="store_true", help="write the dataset (default: dry run)")
    ap.add_argument("--out", type=Path, default=DEFAULT_OUT)
    ap.add_argument("--catalog", type=Path, default=config.CATALOG_FILE)
    ap.add_argument("--diseases", type=str, default=None,
                    help="comma-separated disease list (overrides the catalogue)")
    ap.add_argument("--offline", action="store_true", help="skip the model (built-in fallback)")
    args = ap.parse_args()

    names = load_disease_names(args.catalog, args.diseases)
    dataset = generate(names, offline=args.offline)

    # -- summary -----------------------------------------------------------
    missing = [n for n, s in dataset.items() if not s]
    print(f"\nGenerated symptoms for {len(dataset) - len(missing)}/{len(dataset)} diseases.")
    for name, symptoms in dataset.items():
        print(f"\n{name} ({len(symptoms)}):")
        for s in symptoms:
            print(f"  - {s}")
    if missing:
        print(f"\nWARNING: no symptoms returned for: {', '.join(missing)}")

    if args.apply:
        args.out.parent.mkdir(parents=True, exist_ok=True)
        args.out.write_text(
            json.dumps(dataset, ensure_ascii=False, indent=2) + "\n", encoding="utf-8"
        )
        print(f"\nWrote {args.out}")
    else:
        print("\nDry run - nothing written. Re-run with --apply to save.")


if __name__ == "__main__":
    main()
